name: Upload BentoML Dockerized Model with or without Multi-stage Conda Pack

on:
  workflow_call:
    inputs:
      version:
        required: true
        type: string

jobs:
  build-bentoml-image:
    if: ${{ github.repository != 'ersilia-os/eos-template' }}
    runs-on: ubuntu-latest
    steps:

      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Check if we can use this workflow
        run: |
          if [[ -f install.yml ]]; then
            echo "This workflow is not supported for this repository"
            exit 1
          fi
      
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
    
      # log in to dockerhub
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}

      # This might stop working in the future, so we need to keep an eye on it
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Setup conda
        id: setupConda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10.10"

      - name: Install dependencies in Conda environment
        id: installDependenciesInConda
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install git+https://github.com/ersilia-os/ersilia.git

      - name: Generate the  Dockerfile
        id: generateDockerfile
        env:
          REPO_NAME: ${{ github.event.repository.name }}
          VERSION: ${{ inputs.version}}
        run: |
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/place_a_dockerfile_in_current_eos_repo.py
          python -m pip install requests
          python place_a_dockerfile_in_current_eos_repo.py $REPO_NAME $VERSION
          rm place_a_dockerfile_in_current_eos_repo.py

      - name: Build and push
        id: buildMultiple
        continue-on-error: true
        uses: docker/build-push-action@v6.7.0
        timeout-minutes: 60
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: |
            ersiliaos/${{ github.event.repository.name }}:dev
