name: Upload Legacy Bentoml Dockerized Model

on:
  workflow_call:

jobs:
  build-legacy-bentoml-image:
    if: ${{ github.repository != 'ersilia-os/eos-template' && github.event.workflow_run.conclusion == 'success' }}
    runs-on: ubuntu-latest
    steps:
      # https://github.com/docker/setup-qemu-action
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v3
      
      # https://github.com/docker/setup-buildx-action
      - name: Set up Docker Buildx
        id: buildx
        uses: docker/setup-buildx-action@v3
    
      # log in to dockerhub
      - name: Login to Docker Hub
        if: github.event_name != 'pull_request'
        uses: docker/login-action@v1
        with:
          username: ${{ secrets.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_PASSWORD }}
          
      - name: Checkout persist credentials
        uses: actions/checkout@master
        with:
          persist-credentials: false # otherwise, the token used is the GITHUB_TOKEN, instead of your personal token
          fetch-depth: 0 # otherwise, you will failed to push refs to dest repo
          lfs: 'true'

      # This might stop working in the future, so we need to keep an eye on it
      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          # this might remove tools that are actually needed,
          # if set to "true" but frees about 6 GB
          tool-cache: true
          
          # all of these default to true, but feel free to set to
          # "false" if necessary for your workflow
          android: true
          dotnet: true
          haskell: true
          large-packages: true
          swap-storage: true

      - name: Setup conda
        id: setupConda
        uses: conda-incubator/setup-miniconda@v3
        with:
          auto-update-conda: true
          python-version: "3.10.10"

      - name: Install dependencies in Conda environment
        id: installDependenciesInConda
        run: |
          conda install git-lfs -c conda-forge
          git-lfs install
          conda install gh -c conda-forge
          python -m pip install git+https://github.com/ersilia-os/ersilia.git

      - name: Generate the  Dockerfile
        id: generateDockerfile
        env:
          REPO_NAME: ${{ github.event.repository.name }}
        run: |
          rm Dockerfile # Remove the V2 Dockerfile
          wget https://raw.githubusercontent.com/ersilia-os/ersilia/master/.github/scripts/place_a_dockerfile_in_current_eos_repo.py
          python -m pip install requests
          python place_a_dockerfile_in_current_eos_repo.py $REPO_NAME "legacy-bentoml"
          rm place_a_dockerfile_in_current_eos_repo.py

      # We cannot tag it as anything other than latest because 
      # ersilia cli only looks for the 'latest' tag
      - name: Build only  AMD64 Image for Testing
        id: buildForTest
        uses: docker/build-push-action@v5
        with:
          context: .
          load: true
          tags: ersiliaos/${{ github.event.repository.name }}:latest
          
      # TODO This is very hacky, maybe we want to use the ersilia test command in the future for this
      - name: Test built image
        id: testBuiltImage
        run: |
          ersilia -v fetch ${{ github.event.repository.name }} --from_dockerhub
          ersilia -v serve ${{ github.event.repository.name }}
          ersilia example -n 1 -f input.csv --predefined
          ersilia -v run -i "input.csv" -o "output.csv"
          ersilia close
          output=$(python .github/scripts/verify_model_outcome.py output.csv)
          if echo "$output" | grep -q "All outcomes are null"; then
            echo "Error in model outcome, aborting build"
            exit 1
          fi
          rm output.csv
        env:
          PULL_IMAGE: n

      - name: Build and push
        id: buildMultiple
        continue-on-error: true
        uses: docker/build-push-action@v6.7.0
        timeout-minutes: 45
        with:
          context: .
          platforms: linux/amd64,linux/arm64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ersiliaos/${{ github.event.repository.name }}:latest
          
      - name: Set build failure output
        id: buildCheck
        run: |
          if [[ "${{ steps.buildMultiple.outcome }}" == "failure" ]]; then
            echo "::set-output name=failed::true"
            echo "AMD64" > arch.txt 
          else
            echo "::set-output name=failed::false"
            echo "AMD64,ARM64" > arch.txt
          fi
      
      - name: Upload arch.txt
      uses: actions/upload-artifact@v2
      with:
        name: arch
        path: arch.txt
        
      - name: Build only for Linux/amd64
        id: buildSingle
        if: steps.buildCheck.outputs.failed == 'true'
        uses: docker/build-push-action@v6.7.0
        with:
          context: .
          platforms: linux/amd64
          push: ${{ github.event_name != 'pull_request' }}
          tags: ersiliaos/${{ github.event.repository.name }}:latest